name: Build on Linux
description: Run the CMake build in the build directory

runs:
  using: composite

  steps:
    - name: Build
      shell: bash
      run: |
        cd build
        cmake --build . -- -j$(nproc)
